language: node_js
node_js:
  - lts/*
sudo: false

script:
  - npm run test
  - npm run web

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true